

all: Lect-31.html Lect-32.html Homework-Marlowe.html Lect-33.html Lect-34.html

FR=../01/

Lect-31.html: Lect-31.md
	markdown-cli --input=./Lect-31.md --output=Lect-31.html
	cat ${FR}/css/pre ${FR}/css/markdown.css ${FR}/css/post ../../md.css ${FR}/css/hpre Lect-31.html ${FR}/css/hpost >/tmp/Lect-31.html
	mv /tmp/Lect-31.html ./Lect-31.html

Lect-32.html: Lect-32.md
	markdown-cli --input=./Lect-32.md --output=Lect-32.html
	cat ${FR}/css/pre ${FR}/css/markdown.css ${FR}/css/post ../../md.css ${FR}/css/hpre Lect-32.html ${FR}/css/hpost >/tmp/Lect-32.html
	mv /tmp/Lect-32.html ./Lect-32.html

Lect-33.html: Lect-33.md
	markdown-cli --input=./Lect-33.md --output=Lect-33.html
	cat ${FR}/css/pre ${FR}/css/markdown.css ${FR}/css/post ../../md.css ${FR}/css/hpre Lect-33.html ${FR}/css/hpost >/tmp/Lect-33.html
	mv /tmp/Lect-33.html ./Lect-33.html

Lect-34.html: Lect-34.md
	markdown-cli --input=./Lect-34.md --output=Lect-34.html
	cat ${FR}/css/pre ${FR}/css/markdown.css ${FR}/css/post ../../md.css ${FR}/css/hpre Lect-34.html ${FR}/css/hpost >/tmp/Lect-34.html
	mv /tmp/Lect-34.html ./Lect-34.html



Homework-Marlowe.html: Homework-Marlowe.md
	markdown-cli --input=./Homework-Marlowe.md --output=Homework-Marlowe.html
	cat ${FR}/css/pre ${FR}/css/markdown.css ${FR}/css/post ../../md.css ${FR}/css/hpre Homework-Marlowe.html ${FR}/css/hpost >/tmp/Homework-Marlowe.html
	mv /tmp/Homework-Marlowe.html ./Homework-Marlowe.html


#Homework-Marlow.md
